apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: default
spec:
  params:
    - name: git-url
      default: "https://github.com/aviran355/gitops_demo.git"
    - name: revision
      default: "main"
    - name: image-url
  workspaces:
    - name: output
    - name: github-token
  tasks:
    - name: fetch-source
      workspaces:
        - name: output
        - name: github-token
      params:
        - name: git-url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.revision)"
      taskSpec:
        steps:
          - name: clone-repo
            image: alpine/git
            env:
              - name: GIT_USER
                valueFrom:
                  secretKeyRef:
                    name: github-token
                    key: username
              - name: GIT_PASS
                valueFrom:
                  secretKeyRef:
                    name: github-token
                    key: token
            script: |
              #!/bin/sh
              set -e
              echo "🧹 Cleaning output workspace..."
              rm -rf /workspace/output/*

              echo "🌍 Cloning repository from $(params.git-url)..."
              git clone --branch $(params.revision) --depth=1 https://$GIT_USER:$GIT_PASS@github.com/aviran355/gitops_demo.git /workspace/output/repo

              echo "✅ Repository cloned successfully!"

